const allCountries = [

  // ── EASY (20) ────────────────────────────────────────────────────────────
  { country: "USA",          nameHe: "ארצות הברית",            code: "us", capital: "Washington D.C.", capitalHe: "וושינגטון די.סי.", difficulty: "easy" },
  { country: "UK",           nameHe: "בריטניה",                code: "gb", capital: "London",          capitalHe: "לונדון",           difficulty: "easy" },
  { country: "France",       nameHe: "צרפת",                   code: "fr", capital: "Paris",           capitalHe: "פריז",             difficulty: "easy" },
  { country: "Germany",      nameHe: "גרמניה",                 code: "de", capital: "Berlin",          capitalHe: "ברלין",            difficulty: "easy" },
  { country: "Italy",        nameHe: "איטליה",                 code: "it", capital: "Rome",            capitalHe: "רומא",             difficulty: "easy" },
  { country: "Spain",        nameHe: "ספרד",                   code: "es", capital: "Madrid",          capitalHe: "מדריד",            difficulty: "easy" },
  { country: "Japan",        nameHe: "יפן",                    code: "jp", capital: "Tokyo",           capitalHe: "טוקיו",            difficulty: "easy" },
  { country: "Canada",       nameHe: "קנדה",                   code: "ca", capital: "Ottawa",          capitalHe: "אוטווה",           difficulty: "easy" },
  { country: "Australia",    nameHe: "אוסטרליה",               code: "au", capital: "Canberra",        capitalHe: "קנברה",            difficulty: "easy" },
  { country: "Brazil",       nameHe: "ברזיל",                  code: "br", capital: "Brasília",        capitalHe: "ברזיליה",          difficulty: "easy" },
  { country: "Russia",       nameHe: "רוסיה",                  code: "ru", capital: "Moscow",          capitalHe: "מוסקבה",           difficulty: "easy" },
  { country: "China",        nameHe: "סין",                    code: "cn", capital: "Beijing",         capitalHe: "בייג'ינג",         difficulty: "easy" },
  { country: "India",        nameHe: "הודו",                   code: "in", capital: "New Delhi",       capitalHe: "ניו דלהי",         difficulty: "easy" },
  { country: "Turkey",       nameHe: "טורקיה",                 code: "tr", capital: "Ankara",          capitalHe: "אנקרה",            difficulty: "easy" },
  { country: "South Africa", nameHe: "דרום אפריקה",            code: "za", capital: "Pretoria",        capitalHe: "פרטוריה",          difficulty: "easy" },
  { country: "Mexico",       nameHe: "מקסיקו",                 code: "mx", capital: "Mexico City",     capitalHe: "מקסיקו סיטי",      difficulty: "easy" },
  { country: "Argentina",    nameHe: "ארגנטינה",               code: "ar", capital: "Buenos Aires",    capitalHe: "בואנוס איירס",     difficulty: "easy" },
  { country: "Ukraine",      nameHe: "אוקראינה",               code: "ua", capital: "Kyiv",            capitalHe: "קייב",             difficulty: "easy" },
  { country: "Israel",       nameHe: "ישראל",                  code: "il", capital: "Jerusalem",       capitalHe: "ירושלים",          difficulty: "easy" },
  { country: "South Korea",  nameHe: "קוריאה הדרומית",         code: "kr", capital: "Seoul",           capitalHe: "סיאול",            difficulty: "easy" },

  // ── MEDIUM (49) ──────────────────────────────────────────────────────────

  // Europe
  { country: "Netherlands",  nameHe: "הולנד",                  code: "nl", capital: "Amsterdam",       capitalHe: "אמסטרדם",          difficulty: "medium" },
  { country: "Sweden",       nameHe: "שוודיה",                 code: "se", capital: "Stockholm",       capitalHe: "שטוקהולם",         difficulty: "medium" },
  { country: "Norway",       nameHe: "נורווגיה",               code: "no", capital: "Oslo",            capitalHe: "אוסלו",            difficulty: "medium" },
  { country: "Denmark",      nameHe: "דנמרק",                  code: "dk", capital: "Copenhagen",      capitalHe: "קופנהגן",          difficulty: "medium" },
  { country: "Finland",      nameHe: "פינלנד",                 code: "fi", capital: "Helsinki",        capitalHe: "הלסינקי",          difficulty: "medium" },
  { country: "Portugal",     nameHe: "פורטוגל",                code: "pt", capital: "Lisbon",          capitalHe: "ליסבון",           difficulty: "medium" },
  { country: "Switzerland",  nameHe: "שוויץ",                  code: "ch", capital: "Bern",            capitalHe: "ברן",              difficulty: "medium" },
  { country: "Poland",       nameHe: "פולין",                  code: "pl", capital: "Warsaw",          capitalHe: "ורשה",             difficulty: "medium" },
  { country: "Austria",      nameHe: "אוסטריה",                code: "at", capital: "Vienna",          capitalHe: "וינה",             difficulty: "medium" },
  { country: "Belgium",      nameHe: "בלגיה",                  code: "be", capital: "Brussels",        capitalHe: "בריסל",            difficulty: "medium" },
  { country: "Greece",       nameHe: "יוון",                   code: "gr", capital: "Athens",          capitalHe: "אתונה",            difficulty: "medium" },
  { country: "Hungary",      nameHe: "הונגריה",                code: "hu", capital: "Budapest",        capitalHe: "בודפשט",           difficulty: "medium" },
  { country: "Czech Republic", nameHe: "צ'כיה",               code: "cz", capital: "Prague",          capitalHe: "פראג",             difficulty: "medium" },
  { country: "Romania",      nameHe: "רומניה",                 code: "ro", capital: "Bucharest",       capitalHe: "בוקרשט",           difficulty: "medium" },
  { country: "Ireland",      nameHe: "אירלנד",                 code: "ie", capital: "Dublin",          capitalHe: "דבלין",            difficulty: "medium" },
  { country: "Croatia",      nameHe: "קרואטיה",                code: "hr", capital: "Zagreb",          capitalHe: "זגרב",             difficulty: "medium" },

  // Americas
  { country: "Colombia",     nameHe: "קולומביה",               code: "co", capital: "Bogotá",          capitalHe: "בוגוטה",           difficulty: "medium" },
  { country: "Venezuela",    nameHe: "ונצואלה",                code: "ve", capital: "Caracas",         capitalHe: "קראקס",            difficulty: "medium" },
  { country: "Peru",         nameHe: "פרו",                    code: "pe", capital: "Lima",            capitalHe: "לימה",             difficulty: "medium" },
  { country: "Chile",        nameHe: "צ'ילה",                  code: "cl", capital: "Santiago",        capitalHe: "סנטיאגו",          difficulty: "medium" },
  { country: "Cuba",         nameHe: "קובה",                   code: "cu", capital: "Havana",          capitalHe: "הוואנה",           difficulty: "medium" },
  { country: "Jamaica",      nameHe: "ג'מייקה",                code: "jm", capital: "Kingston",        capitalHe: "קינגסטון",         difficulty: "medium" },
  { country: "Bolivia",      nameHe: "בוליביה",                code: "bo", capital: "Sucre",           capitalHe: "סוקרה",            difficulty: "medium" },

  // Asia / Middle East
  { country: "Thailand",     nameHe: "תאילנד",                 code: "th", capital: "Bangkok",         capitalHe: "בנגקוק",           difficulty: "medium" },
  { country: "Saudi Arabia", nameHe: "ערב הסעודית",            code: "sa", capital: "Riyadh",          capitalHe: "ריאד",             difficulty: "medium" },
  { country: "Indonesia",    nameHe: "אינדונזיה",              code: "id", capital: "Jakarta",         capitalHe: "ג'קרטה",           difficulty: "medium" },
  { country: "Pakistan",     nameHe: "פקיסטן",                 code: "pk", capital: "Islamabad",       capitalHe: "איסלמאבד",         difficulty: "medium" },
  { country: "Philippines",  nameHe: "פיליפינים",              code: "ph", capital: "Manila",          capitalHe: "מנילה",            difficulty: "medium" },
  { country: "Vietnam",      nameHe: "וייטנאם",                code: "vn", capital: "Hanoi",           capitalHe: "האנוי",            difficulty: "medium" },
  { country: "Malaysia",     nameHe: "מלזיה",                  code: "my", capital: "Kuala Lumpur",    capitalHe: "קואלה לומפור",     difficulty: "medium" },
  { country: "Singapore",    nameHe: "סינגפור",                code: "sg", capital: "Singapore",       capitalHe: "סינגפור",          difficulty: "medium" },
  { country: "UAE",          nameHe: "איחוד האמירויות",        code: "ae", capital: "Abu Dhabi",       capitalHe: "אבו דאבי",         difficulty: "medium" },
  { country: "Iran",         nameHe: "איראן",                  code: "ir", capital: "Tehran",          capitalHe: "טהראן",            difficulty: "medium" },
  { country: "Iraq",         nameHe: "עיראק",                  code: "iq", capital: "Baghdad",         capitalHe: "בגדד",             difficulty: "medium" },
  { country: "New Zealand",  nameHe: "ניו זילנד",              code: "nz", capital: "Wellington",      capitalHe: "וולינגטון",        difficulty: "medium" },

  // Africa
  { country: "Egypt",        nameHe: "מצרים",                  code: "eg", capital: "Cairo",           capitalHe: "קהיר",             difficulty: "medium" },
  { country: "Nigeria",      nameHe: "ניגריה",                 code: "ng", capital: "Abuja",           capitalHe: "אבוג'ה",           difficulty: "medium" },
  { country: "Morocco",      nameHe: "מרוקו",                  code: "ma", capital: "Rabat",           capitalHe: "רבאט",             difficulty: "medium" },
  { country: "Kenya",        nameHe: "קניה",                   code: "ke", capital: "Nairobi",         capitalHe: "ניירובי",          difficulty: "medium" },
  { country: "Ghana",        nameHe: "גאנה",                   code: "gh", capital: "Accra",           capitalHe: "אקרה",             difficulty: "medium" },
  { country: "Ethiopia",     nameHe: "אתיופיה",                code: "et", capital: "Addis Ababa",     capitalHe: "אדיס אבבה",        difficulty: "medium" },
  { country: "Tunisia",      nameHe: "תוניסיה",                code: "tn", capital: "Tunis",           capitalHe: "תוניס",            difficulty: "medium" },
  { country: "Tanzania",     nameHe: "טנזניה",                 code: "tz", capital: "Dodoma",          capitalHe: "דודומה",           difficulty: "medium" },
  { country: "Cameroon",     nameHe: "קמרון",                  code: "cm", capital: "Yaoundé",         capitalHe: "יאונדה",           difficulty: "medium" },
  { country: "Senegal",      nameHe: "סנגל",                   code: "sn", capital: "Dakar",           capitalHe: "דקר",              difficulty: "medium" },
  { country: "Algeria",      nameHe: "אלג'יריה",               code: "dz", capital: "Algiers",         capitalHe: "אלג'יר",           difficulty: "medium" },
  { country: "Ivory Coast",  nameHe: "חוף השנהב",              code: "ci", capital: "Yamoussoukro",    capitalHe: "יאמוסוקרו",        difficulty: "medium" },
  { country: "Angola",       nameHe: "אנגולה",                 code: "ao", capital: "Luanda",          capitalHe: "לואנדה",           difficulty: "medium" },
  { country: "Zimbabwe",     nameHe: "זימבבואה",               code: "zw", capital: "Harare",          capitalHe: "הררה",             difficulty: "medium" },

  // ── HARD (126) ───────────────────────────────────────────────────────────

  // Europe
  { country: "Albania",      nameHe: "אלבניה",                 code: "al", capital: "Tirana",          capitalHe: "טירנה",            difficulty: "hard" },
  { country: "Andorra",      nameHe: "אנדורה",                 code: "ad", capital: "Andorra la Vella", capitalHe: "אנדורה לה ולה",  difficulty: "hard" },
  { country: "Armenia",      nameHe: "ארמניה",                 code: "am", capital: "Yerevan",         capitalHe: "ירוואן",           difficulty: "hard" },
  { country: "Azerbaijan",   nameHe: "אזרבייג'ן",              code: "az", capital: "Baku",            capitalHe: "באקו",             difficulty: "hard" },
  { country: "Belarus",      nameHe: "בלארוס",                 code: "by", capital: "Minsk",           capitalHe: "מינסק",            difficulty: "hard" },
  { country: "Bosnia & Herzegovina", nameHe: "בוסניה והרצגובינה", code: "ba", capital: "Sarajevo",   capitalHe: "סרייבו",           difficulty: "hard" },
  { country: "Bulgaria",     nameHe: "בולגריה",                code: "bg", capital: "Sofia",           capitalHe: "סופיה",            difficulty: "hard" },
  { country: "Cyprus",       nameHe: "קפריסין",                code: "cy", capital: "Nicosia",         capitalHe: "ניקוסיה",          difficulty: "hard" },
  { country: "Estonia",      nameHe: "אסטוניה",                code: "ee", capital: "Tallinn",         capitalHe: "טאלין",            difficulty: "hard" },
  { country: "Georgia",      nameHe: "גאורגיה",                code: "ge", capital: "Tbilisi",         capitalHe: "טביליסי",          difficulty: "hard" },
  { country: "Iceland",      nameHe: "איסלנד",                 code: "is", capital: "Reykjavik",       capitalHe: "רייקיאוויק",       difficulty: "hard" },
  { country: "Latvia",       nameHe: "לטביה",                  code: "lv", capital: "Riga",            capitalHe: "ריגה",             difficulty: "hard" },
  { country: "Liechtenstein", nameHe: "ליכטנשטיין",           code: "li", capital: "Vaduz",           capitalHe: "ואדוץ",            difficulty: "hard" },
  { country: "Lithuania",    nameHe: "ליטא",                   code: "lt", capital: "Vilnius",         capitalHe: "וילניוס",          difficulty: "hard" },
  { country: "Luxembourg",   nameHe: "לוקסמבורג",              code: "lu", capital: "Luxembourg City", capitalHe: "לוקסמבורג",        difficulty: "hard" },
  { country: "Malta",        nameHe: "מלטה",                   code: "mt", capital: "Valletta",        capitalHe: "ולטה",             difficulty: "hard" },
  { country: "Moldova",      nameHe: "מולדובה",                code: "md", capital: "Chișinău",        capitalHe: "קישינב",           difficulty: "hard" },
  { country: "Monaco",       nameHe: "מונקו",                  code: "mc", capital: "Monaco",          capitalHe: "מונקו",            difficulty: "hard" },
  { country: "Montenegro",   nameHe: "מונטנגרו",               code: "me", capital: "Podgorica",       capitalHe: "פודגוריצה",        difficulty: "hard" },
  { country: "North Macedonia", nameHe: "מקדוניה הצפונית",    code: "mk", capital: "Skopje",          capitalHe: "סקופיה",           difficulty: "hard" },
  { country: "San Marino",   nameHe: "סן מרינו",               code: "sm", capital: "San Marino",      capitalHe: "סן מרינו",         difficulty: "hard" },
  { country: "Serbia",       nameHe: "סרביה",                  code: "rs", capital: "Belgrade",        capitalHe: "בלגרד",            difficulty: "hard" },
  { country: "Slovakia",     nameHe: "סלובקיה",                code: "sk", capital: "Bratislava",      capitalHe: "ברטיסלבה",         difficulty: "hard" },
  { country: "Slovenia",     nameHe: "סלובניה",                code: "si", capital: "Ljubljana",       capitalHe: "לובליאנה",         difficulty: "hard" },
  { country: "Chad",         nameHe: "צ'אד",                   code: "td", capital: "N'Djamena",       capitalHe: "נג'מנה",           difficulty: "hard" },
  { country: "Mali",         nameHe: "מאלי",                   code: "ml", capital: "Bamako",          capitalHe: "במאקו",            difficulty: "hard" },
  { country: "Kosovo",       nameHe: "קוסובו",                 code: "xk", capital: "Pristina",        capitalHe: "פרישטינה",         difficulty: "hard" },

  // Americas
  { country: "Antigua & Barbuda", nameHe: "אנטיגואה וברבודה",  code: "ag", capital: "Saint John's",   capitalHe: "סנט ג'ונס",        difficulty: "hard" },
  { country: "Bahamas",      nameHe: "איי בהאמה",              code: "bs", capital: "Nassau",          capitalHe: "נסאו",             difficulty: "hard" },
  { country: "Barbados",     nameHe: "ברבדוס",                 code: "bb", capital: "Bridgetown",      capitalHe: "בריג'טאון",        difficulty: "hard" },
  { country: "Belize",       nameHe: "בליז",                   code: "bz", capital: "Belmopan",        capitalHe: "בלמופן",           difficulty: "hard" },
  { country: "Costa Rica",   nameHe: "קוסטה ריקה",             code: "cr", capital: "San José",        capitalHe: "סן חוסה",          difficulty: "hard" },
  { country: "Dominica",     nameHe: "דומיניקה",               code: "dm", capital: "Roseau",          capitalHe: "רוזו",             difficulty: "hard" },
  { country: "Dominican Republic", nameHe: "הרפובליקה הדומיניקנית", code: "do", capital: "Santo Domingo", capitalHe: "סנטו דומינגו", difficulty: "hard" },
  { country: "Ecuador",      nameHe: "אקוודור",                code: "ec", capital: "Quito",           capitalHe: "קיטו",             difficulty: "hard" },
  { country: "El Salvador",  nameHe: "אל סלוודור",             code: "sv", capital: "San Salvador",    capitalHe: "סן סלוודור",       difficulty: "hard" },
  { country: "Grenada",      nameHe: "גרנדה",                  code: "gd", capital: "Saint George's",  capitalHe: "סנט ג'ורג'",       difficulty: "hard" },
  { country: "Guatemala",    nameHe: "גואטמלה",                code: "gt", capital: "Guatemala City",  capitalHe: "גואטמלה סיטי",     difficulty: "hard" },
  { country: "Guyana",       nameHe: "גויאנה",                 code: "gy", capital: "Georgetown",      capitalHe: "ג'ורג'טאון",       difficulty: "hard" },
  { country: "Haiti",        nameHe: "האיטי",                  code: "ht", capital: "Port-au-Prince",  capitalHe: "פורט או פרנס",     difficulty: "hard" },
  { country: "Honduras",     nameHe: "הונדורס",                code: "hn", capital: "Tegucigalpa",     capitalHe: "טגוסיגלפה",        difficulty: "hard" },
  { country: "Nicaragua",    nameHe: "ניקרגואה",               code: "ni", capital: "Managua",         capitalHe: "מנגואה",           difficulty: "hard" },
  { country: "Panama",       nameHe: "פנמה",                   code: "pa", capital: "Panama City",     capitalHe: "פנמה סיטי",        difficulty: "hard" },
  { country: "Paraguay",     nameHe: "פרגוואי",                code: "py", capital: "Asunción",        capitalHe: "אסונסיון",         difficulty: "hard" },
  { country: "Saint Kitts & Nevis", nameHe: "סנט קיטס ונוויס", code: "kn", capital: "Basseterre",     capitalHe: "בסטר",             difficulty: "hard" },
  { country: "Saint Lucia",  nameHe: "סנט לוסיה",              code: "lc", capital: "Castries",        capitalHe: "קסטריז",           difficulty: "hard" },
  { country: "Saint Vincent", nameHe: "סנט וינסנט",            code: "vc", capital: "Kingstown",       capitalHe: "קינגסטאון",        difficulty: "hard" },
  { country: "Suriname",     nameHe: "סורינאם",                code: "sr", capital: "Paramaribo",      capitalHe: "פרמריבו",          difficulty: "hard" },
  { country: "Trinidad & Tobago", nameHe: "טרינידד וטובגו",    code: "tt", capital: "Port of Spain",   capitalHe: "פורט אוף ספיין",   difficulty: "hard" },
  { country: "Uruguay",      nameHe: "אורוגוואי",              code: "uy", capital: "Montevideo",      capitalHe: "מונטווידאו",       difficulty: "hard" },

  // Asia
  { country: "Afghanistan",  nameHe: "אפגניסטן",               code: "af", capital: "Kabul",           capitalHe: "קאבול",            difficulty: "hard" },
  { country: "Bahrain",      nameHe: "בחריין",                 code: "bh", capital: "Manama",          capitalHe: "מנמה",             difficulty: "hard" },
  { country: "Bangladesh",   nameHe: "בנגלדש",                 code: "bd", capital: "Dhaka",           capitalHe: "דאקה",             difficulty: "hard" },
  { country: "Bhutan",       nameHe: "בהוטן",                  code: "bt", capital: "Thimphu",         capitalHe: "תימפו",            difficulty: "hard" },
  { country: "Brunei",       nameHe: "ברוניי",                 code: "bn", capital: "Bandar Seri Begawan", capitalHe: "בנדר סרי בגאוון", difficulty: "hard" },
  { country: "Cambodia",     nameHe: "קמבודיה",                code: "kh", capital: "Phnom Penh",      capitalHe: "פנום פן",          difficulty: "hard" },
  { country: "Jordan",       nameHe: "ירדן",                   code: "jo", capital: "Amman",           capitalHe: "עמאן",             difficulty: "hard" },
  { country: "Kazakhstan",   nameHe: "קזחסטן",                 code: "kz", capital: "Astana",          capitalHe: "אסטנה",            difficulty: "hard" },
  { country: "Kuwait",       nameHe: "כווית",                  code: "kw", capital: "Kuwait City",     capitalHe: "כווית סיטי",       difficulty: "hard" },
  { country: "Kyrgyzstan",   nameHe: "קירגיזסטן",              code: "kg", capital: "Bishkek",         capitalHe: "בישקק",            difficulty: "hard" },
  { country: "Laos",         nameHe: "לאוס",                   code: "la", capital: "Vientiane",       capitalHe: "ויינטיאן",         difficulty: "hard" },
  { country: "Lebanon",      nameHe: "לבנון",                  code: "lb", capital: "Beirut",          capitalHe: "ביירות",           difficulty: "hard" },
  { country: "Maldives",     nameHe: "האיים המלדיביים",        code: "mv", capital: "Malé",            capitalHe: "מאלה",             difficulty: "hard" },
  { country: "Mongolia",     nameHe: "מונגוליה",               code: "mn", capital: "Ulaanbaatar",     capitalHe: "אולן בטור",        difficulty: "hard" },
  { country: "Myanmar",      nameHe: "מיאנמר",                 code: "mm", capital: "Naypyidaw",       capitalHe: "נייפידו",          difficulty: "hard" },
  { country: "Nepal",        nameHe: "נפאל",                   code: "np", capital: "Kathmandu",       capitalHe: "קטמנדו",           difficulty: "hard" },
  { country: "North Korea",  nameHe: "קוריאה הצפונית",         code: "kp", capital: "Pyongyang",       capitalHe: "פיונגיאנג",        difficulty: "hard" },
  { country: "Oman",         nameHe: "עומאן",                  code: "om", capital: "Muscat",          capitalHe: "מסקט",             difficulty: "hard" },
  { country: "Qatar",        nameHe: "קטר",                    code: "qa", capital: "Doha",            capitalHe: "דוחה",             difficulty: "hard" },
  { country: "Sri Lanka",    nameHe: "סרי לנקה",               code: "lk", capital: "Colombo",         capitalHe: "קולומבו",          difficulty: "hard" },
  { country: "Syria",        nameHe: "סוריה",                  code: "sy", capital: "Damascus",        capitalHe: "דמשק",             difficulty: "hard" },
  { country: "Taiwan",       nameHe: "טייוואן",                code: "tw", capital: "Taipei",          capitalHe: "טייפיי",           difficulty: "hard" },
  { country: "Tajikistan",   nameHe: "טג'יקיסטן",              code: "tj", capital: "Dushanbe",        capitalHe: "דושנבה",           difficulty: "hard" },
  { country: "Timor-Leste",  nameHe: "טימור-לסטה",             code: "tl", capital: "Dili",            capitalHe: "דילי",             difficulty: "hard" },
  { country: "Turkmenistan", nameHe: "טורקמניסטן",             code: "tm", capital: "Ashgabat",        capitalHe: "עשקאבד",           difficulty: "hard" },
  { country: "Uzbekistan",   nameHe: "אוזבקיסטן",              code: "uz", capital: "Tashkent",        capitalHe: "טשקנט",            difficulty: "hard" },
  { country: "Yemen",        nameHe: "תימן",                   code: "ye", capital: "Sana'a",          capitalHe: "סנעא",             difficulty: "hard" },

  // Africa
  { country: "Benin",        nameHe: "בנין",                   code: "bj", capital: "Porto-Novo",      capitalHe: "פורטו-נובו",       difficulty: "hard" },
  { country: "Botswana",     nameHe: "בוצואנה",                code: "bw", capital: "Gaborone",        capitalHe: "גבורונה",          difficulty: "hard" },
  { country: "Burkina Faso", nameHe: "בורקינה פאסו",           code: "bf", capital: "Ouagadougou",     capitalHe: "וואגאדוגו",        difficulty: "hard" },
  { country: "Burundi",      nameHe: "בורונדי",                code: "bi", capital: "Gitega",          capitalHe: "גיטגה",            difficulty: "hard" },
  { country: "Cape Verde",   nameHe: "כף ורדה",                code: "cv", capital: "Praia",           capitalHe: "פראיה",            difficulty: "hard" },
  { country: "Central African Republic", nameHe: "הרפובליקה המרכז-אפריקאית", code: "cf", capital: "Bangui", capitalHe: "בנגי",    difficulty: "hard" },
  { country: "Comoros",      nameHe: "קומורו",                 code: "km", capital: "Moroni",          capitalHe: "מורוני",           difficulty: "hard" },
  { country: "DR Congo",     nameHe: "קונגו הדמוקרטית",        code: "cd", capital: "Kinshasa",        capitalHe: "קינשאסה",          difficulty: "hard" },
  { country: "Republic of Congo", nameHe: "הרפובליקה של קונגו", code: "cg", capital: "Brazzaville",   capitalHe: "ברזוויל",          difficulty: "hard" },
  { country: "Djibouti",     nameHe: "ג'יבוטי",                code: "dj", capital: "Djibouti",        capitalHe: "ג'יבוטי",          difficulty: "hard" },
  { country: "Equatorial Guinea", nameHe: "גינאה המשוונית",    code: "gq", capital: "Malabo",          capitalHe: "מלאבו",            difficulty: "hard" },
  { country: "Eritrea",      nameHe: "אריתריאה",               code: "er", capital: "Asmara",          capitalHe: "אסמרה",            difficulty: "hard" },
  { country: "Eswatini",     nameHe: "אסווטיני",               code: "sz", capital: "Mbabane",         capitalHe: "מבבנה",            difficulty: "hard" },
  { country: "Gabon",        nameHe: "גבון",                   code: "ga", capital: "Libreville",      capitalHe: "ליברוויל",         difficulty: "hard" },
  { country: "Gambia",       nameHe: "גמביה",                  code: "gm", capital: "Banjul",          capitalHe: "בנג'ול",           difficulty: "hard" },
  { country: "Guinea",       nameHe: "גינאה",                  code: "gn", capital: "Conakry",         capitalHe: "קונקרי",           difficulty: "hard" },
  { country: "Guinea-Bissau", nameHe: "גינאה-ביסאו",           code: "gw", capital: "Bissau",          capitalHe: "ביסאו",            difficulty: "hard" },
  { country: "Lesotho",      nameHe: "לסוטו",                  code: "ls", capital: "Maseru",          capitalHe: "מסרו",             difficulty: "hard" },
  { country: "Liberia",      nameHe: "ליבריה",                 code: "lr", capital: "Monrovia",        capitalHe: "מונרוביה",         difficulty: "hard" },
  { country: "Libya",        nameHe: "לוב",                    code: "ly", capital: "Tripoli",         capitalHe: "טריפולי",          difficulty: "hard" },
  { country: "Madagascar",   nameHe: "מדגסקר",                 code: "mg", capital: "Antananarivo",    capitalHe: "אנטנאנריבו",       difficulty: "hard" },
  { country: "Malawi",       nameHe: "מלאווי",                 code: "mw", capital: "Lilongwe",        capitalHe: "לילונגווה",        difficulty: "hard" },
  { country: "Mauritania",   nameHe: "מאוריטניה",              code: "mr", capital: "Nouakchott",      capitalHe: "נואקשוט",          difficulty: "hard" },
  { country: "Mauritius",    nameHe: "מאוריציוס",              code: "mu", capital: "Port Louis",      capitalHe: "פורט לואיס",       difficulty: "hard" },
  { country: "Mozambique",   nameHe: "מוזמביק",                code: "mz", capital: "Maputo",          capitalHe: "מאפוטו",           difficulty: "hard" },
  { country: "Namibia",      nameHe: "נמיביה",                 code: "na", capital: "Windhoek",        capitalHe: "וינדהוק",          difficulty: "hard" },
  { country: "Niger",        nameHe: "ניז'ר",                  code: "ne", capital: "Niamey",          capitalHe: "ניאמיי",           difficulty: "hard" },
  { country: "Rwanda",       nameHe: "רואנדה",                 code: "rw", capital: "Kigali",          capitalHe: "קיגלי",            difficulty: "hard" },
  { country: "Sao Tome & Principe", nameHe: "סאו טומה ופרינסיפה", code: "st", capital: "São Tomé",    capitalHe: "סאו טומה",         difficulty: "hard" },
  { country: "Seychelles",   nameHe: "סיישל",                  code: "sc", capital: "Victoria",        capitalHe: "ויקטוריה",         difficulty: "hard" },
  { country: "Sierra Leone", nameHe: "סיירה לאונה",            code: "sl", capital: "Freetown",        capitalHe: "פריטאון",          difficulty: "hard" },
  { country: "Somalia",      nameHe: "סומליה",                 code: "so", capital: "Mogadishu",       capitalHe: "מוגדישו",          difficulty: "hard" },
  { country: "South Sudan",  nameHe: "דרום סודן",              code: "ss", capital: "Juba",            capitalHe: "ג'ובה",            difficulty: "hard" },
  { country: "Sudan",        nameHe: "סודן",                   code: "sd", capital: "Khartoum",        capitalHe: "חרטום",            difficulty: "hard" },
  { country: "Togo",         nameHe: "טוגו",                   code: "tg", capital: "Lomé",            capitalHe: "לומה",             difficulty: "hard" },
  { country: "Uganda",       nameHe: "אוגנדה",                 code: "ug", capital: "Kampala",         capitalHe: "קמפלה",            difficulty: "hard" },
  { country: "Zambia",       nameHe: "זמביה",                  code: "zm", capital: "Lusaka",          capitalHe: "לוסקה",            difficulty: "hard" },

  // Oceania
  { country: "Fiji",         nameHe: "פיג'י",                  code: "fj", capital: "Suva",            capitalHe: "סובה",             difficulty: "hard" },
  { country: "Kiribati",     nameHe: "קיריבאטי",               code: "ki", capital: "South Tarawa",    capitalHe: "דרום טאראווה",     difficulty: "hard" },
  { country: "Marshall Islands", nameHe: "איי מרשל",           code: "mh", capital: "Majuro",          capitalHe: "מג'ורו",           difficulty: "hard" },
  { country: "Micronesia",   nameHe: "מיקרונזיה",              code: "fm", capital: "Palikir",         capitalHe: "פליקיר",           difficulty: "hard" },
  { country: "Nauru",        nameHe: "נאורו",                  code: "nr", capital: "Yaren",           capitalHe: "יארן",             difficulty: "hard" },
  { country: "Palau",        nameHe: "פלאו",                   code: "pw", capital: "Ngerulmud",       capitalHe: "נגרולמוד",         difficulty: "hard" },
  { country: "Papua New Guinea", nameHe: "פפואה גינאה החדשה",  code: "pg", capital: "Port Moresby",    capitalHe: "פורט מורסבי",      difficulty: "hard" },
  { country: "Samoa",        nameHe: "סמואה",                  code: "ws", capital: "Apia",            capitalHe: "אפיה",             difficulty: "hard" },
  { country: "Solomon Islands", nameHe: "איי שלמה",            code: "sb", capital: "Honiara",         capitalHe: "הוניארה",          difficulty: "hard" },
  { country: "Tonga",        nameHe: "טונגה",                  code: "to", capital: "Nukuʻalofa",      capitalHe: "נוקואלופה",        difficulty: "hard" },
  { country: "Tuvalu",       nameHe: "טובלו",                  code: "tv", capital: "Funafuti",        capitalHe: "פונאפוטי",         difficulty: "hard" },
  { country: "Vanuatu",      nameHe: "ונואטו",                 code: "vu", capital: "Port Vila",       capitalHe: "פורט וילה",        difficulty: "hard" },

];
