// 50 US states — flags via flagcdn.com (us-XX format), fips for map rendering
// Difficulty: easy=8 most recognizable, medium=+20, hard=remaining 22

const usStates = [
  { code: "us-al", fips: 1,  name: "Alabama",        nameHe: "אלבמה",           capital: "Montgomery",   capitalHe: "מונטגומרי",     difficulty: "hard"   },
  { code: "us-ak", fips: 2,  name: "Alaska",          nameHe: "אלסקה",           capital: "Juneau",       capitalHe: "ג׳ונו",         difficulty: "easy"   },
  { code: "us-az", fips: 4,  name: "Arizona",         nameHe: "אריזונה",          capital: "Phoenix",      capitalHe: "פיניקס",        difficulty: "medium" },
  { code: "us-ar", fips: 5,  name: "Arkansas",        nameHe: "ארקנסו",           capital: "Little Rock",  capitalHe: "ליטל רוק",      difficulty: "hard"   },
  { code: "us-ca", fips: 6,  name: "California",      nameHe: "קליפורניה",        capital: "Sacramento",   capitalHe: "סקרמנטו",       difficulty: "easy"   },
  { code: "us-co", fips: 8,  name: "Colorado",        nameHe: "קולורדו",          capital: "Denver",       capitalHe: "דנוור",         difficulty: "medium" },
  { code: "us-ct", fips: 9,  name: "Connecticut",     nameHe: "קונטיקט",          capital: "Hartford",     capitalHe: "הארטפורד",      difficulty: "hard"   },
  { code: "us-de", fips: 10, name: "Delaware",        nameHe: "דלאוור",           capital: "Dover",        capitalHe: "דובר",          difficulty: "hard"   },
  { code: "us-fl", fips: 12, name: "Florida",         nameHe: "פלורידה",          capital: "Tallahassee",  capitalHe: "טלהסי",         difficulty: "easy"   },
  { code: "us-ga", fips: 13, name: "Georgia",         nameHe: "ג׳ורג׳יה",         capital: "Atlanta",      capitalHe: "אטלנטה",        difficulty: "medium" },
  { code: "us-hi", fips: 15, name: "Hawaii",          nameHe: "הוואי",            capital: "Honolulu",     capitalHe: "הונולולו",      difficulty: "easy"   },
  { code: "us-id", fips: 16, name: "Idaho",           nameHe: "איידהו",           capital: "Boise",        capitalHe: "בויסי",         difficulty: "hard"   },
  { code: "us-il", fips: 17, name: "Illinois",        nameHe: "אילינוי",          capital: "Springfield",  capitalHe: "ספרינגפילד",    difficulty: "easy"   },
  { code: "us-in", fips: 18, name: "Indiana",         nameHe: "אינדיאנה",         capital: "Indianapolis", capitalHe: "אינדיאנפוליס",  difficulty: "medium" },
  { code: "us-ia", fips: 19, name: "Iowa",            nameHe: "איווה",            capital: "Des Moines",   capitalHe: "דה מוין",       difficulty: "hard"   },
  { code: "us-ks", fips: 20, name: "Kansas",          nameHe: "קנזס",             capital: "Topeka",       capitalHe: "טופיקה",        difficulty: "hard"   },
  { code: "us-ky", fips: 21, name: "Kentucky",        nameHe: "קנטאקי",           capital: "Frankfort",    capitalHe: "פרנקפורט",      difficulty: "hard"   },
  { code: "us-la", fips: 22, name: "Louisiana",       nameHe: "לואיזיאנה",        capital: "Baton Rouge",  capitalHe: "באטון רוז",     difficulty: "medium" },
  { code: "us-me", fips: 23, name: "Maine",           nameHe: "מיין",             capital: "Augusta",      capitalHe: "אוגוסטה",       difficulty: "hard"   },
  { code: "us-md", fips: 24, name: "Maryland",        nameHe: "מרילנד",           capital: "Annapolis",    capitalHe: "אנפוליס",       difficulty: "medium" },
  { code: "us-ma", fips: 25, name: "Massachusetts",   nameHe: "מסצ׳וסטס",         capital: "Boston",       capitalHe: "בוסטון",        difficulty: "medium" },
  { code: "us-mi", fips: 26, name: "Michigan",        nameHe: "מישיגן",           capital: "Lansing",      capitalHe: "לנסינג",        difficulty: "medium" },
  { code: "us-mn", fips: 27, name: "Minnesota",       nameHe: "מינסוטה",          capital: "Saint Paul",   capitalHe: "סנט פול",       difficulty: "medium" },
  { code: "us-ms", fips: 28, name: "Mississippi",     nameHe: "מיסיסיפי",         capital: "Jackson",      capitalHe: "ג׳קסון",        difficulty: "hard"   },
  { code: "us-mo", fips: 29, name: "Missouri",        nameHe: "מיזורי",           capital: "Jefferson City",capitalHe: "ג׳פרסון סיטי", difficulty: "medium" },
  { code: "us-mt", fips: 30, name: "Montana",         nameHe: "מונטנה",           capital: "Helena",       capitalHe: "הלנה",          difficulty: "medium" },
  { code: "us-ne", fips: 31, name: "Nebraska",        nameHe: "נברסקה",           capital: "Lincoln",      capitalHe: "לינקולן",       difficulty: "hard"   },
  { code: "us-nv", fips: 32, name: "Nevada",          nameHe: "נבדה",             capital: "Carson City",  capitalHe: "קרסון סיטי",    difficulty: "medium" },
  { code: "us-nh", fips: 33, name: "New Hampshire",   nameHe: "ניו המפשייר",      capital: "Concord",      capitalHe: "קונקורד",       difficulty: "hard"   },
  { code: "us-nj", fips: 34, name: "New Jersey",      nameHe: "ניו ג׳רזי",        capital: "Trenton",      capitalHe: "טרנטון",        difficulty: "hard"   },
  { code: "us-nm", fips: 35, name: "New Mexico",      nameHe: "ניו מקסיקו",       capital: "Santa Fe",     capitalHe: "סנטה פה",       difficulty: "hard"   },
  { code: "us-ny", fips: 36, name: "New York",        nameHe: "ניו יורק",         capital: "Albany",       capitalHe: "אולבני",        difficulty: "easy"   },
  { code: "us-nc", fips: 37, name: "North Carolina",  nameHe: "צפון קרוליינה",    capital: "Raleigh",      capitalHe: "ראלי",          difficulty: "medium" },
  { code: "us-nd", fips: 38, name: "North Dakota",    nameHe: "צפון דקוטה",       capital: "Bismarck",     capitalHe: "ביסמרק",        difficulty: "hard"   },
  { code: "us-oh", fips: 39, name: "Ohio",            nameHe: "אוהיו",            capital: "Columbus",     capitalHe: "קולומבוס",      difficulty: "medium" },
  { code: "us-ok", fips: 40, name: "Oklahoma",        nameHe: "אוקלהומה",         capital: "Oklahoma City",capitalHe: "אוקלהומה סיטי", difficulty: "hard"   },
  { code: "us-or", fips: 41, name: "Oregon",          nameHe: "אורגון",           capital: "Salem",        capitalHe: "סאלם",          difficulty: "medium" },
  { code: "us-pa", fips: 42, name: "Pennsylvania",    nameHe: "פנסילבניה",        capital: "Harrisburg",   capitalHe: "הריסבורג",      difficulty: "medium" },
  { code: "us-ri", fips: 44, name: "Rhode Island",    nameHe: "רוד איילנד",       capital: "Providence",   capitalHe: "פרובידנס",      difficulty: "hard"   },
  { code: "us-sc", fips: 45, name: "South Carolina",  nameHe: "דרום קרוליינה",    capital: "Columbia",     capitalHe: "קולומביה",      difficulty: "hard"   },
  { code: "us-sd", fips: 46, name: "South Dakota",    nameHe: "דרום דקוטה",       capital: "Pierre",       capitalHe: "פייר",          difficulty: "hard"   },
  { code: "us-tn", fips: 47, name: "Tennessee",       nameHe: "טנסי",             capital: "Nashville",    capitalHe: "נשוויל",        difficulty: "medium" },
  { code: "us-tx", fips: 48, name: "Texas",           nameHe: "טקסס",             capital: "Austin",       capitalHe: "אוסטין",        difficulty: "easy"   },
  { code: "us-ut", fips: 49, name: "Utah",            nameHe: "יוטה",             capital: "Salt Lake City",capitalHe: "סולט לייק סיטי",difficulty: "medium" },
  { code: "us-vt", fips: 50, name: "Vermont",         nameHe: "ורמונט",           capital: "Montpelier",   capitalHe: "מונפלייה",      difficulty: "hard"   },
  { code: "us-va", fips: 51, name: "Virginia",        nameHe: "וירג׳יניה",        capital: "Richmond",     capitalHe: "ריצ׳מונד",      difficulty: "medium" },
  { code: "us-wa", fips: 53, name: "Washington",      nameHe: "וושינגטון",        capital: "Olympia",      capitalHe: "אולימפיה",      difficulty: "easy"   },
  { code: "us-wv", fips: 54, name: "West Virginia",   nameHe: "מערב וירג׳יניה",   capital: "Charleston",   capitalHe: "צ׳ארלסטון",     difficulty: "hard"   },
  { code: "us-wi", fips: 55, name: "Wisconsin",       nameHe: "ויסקונסין",        capital: "Madison",      capitalHe: "מדיסון",        difficulty: "medium" },
  { code: "us-wy", fips: 56, name: "Wyoming",         nameHe: "ויומינג",          capital: "Cheyenne",     capitalHe: "שיאן",          difficulty: "hard"   },
];
